# Generated by Django 3.2.10 on 2024-01-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0003_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('book', models.ManyToManyField(to='BookApp.Book')),
            ],
        ),
    ]
